-- 코드를 작성해주세요
SELECT
    G3.ID
FROM
    ECOLI_DATA AS G3
JOIN
    ECOLI_DATA AS G2 ON G3.PARENT_ID = G2.ID
JOIN
    ECOLI_DATA AS G1 ON G2.PARENT_ID = G1.ID
WHERE
    G1.PARENT_ID IS NULL
ORDER BY
    G3.ID ASC;