-- PRODCUT : PRODUCT_ID(상품ID), PRODUCT_CODE(상품코드), PRICE(판매가)
-- OFFLINE_SALE : OFFLINE_SALE_ID(오프라인상품판매ID), PRODUCT_ID(상품ID), SALES_AMOUNT(판매량)
-- SALES_DATE(판매일)

SELECT PD.PRODUCT_CODE, SUM(PD.PRICE * OS.SALES_AMOUNT) SALES
FROM PRODUCT      PD
JOIN OFFLINE_SALE OS ON PD.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PD.PRODUCT_CODE
ORDER BY SALES DESC, PD.PRODUCT_CODE ASC