-- MEMBER_PROFILE : 
-- MEMBER_ID(회원ID), MEMBER_NAME(회원이름), TLNO(회원연락처), GENDER(성별), DATE_OF_BIRTH(생년월일)

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE DATE_FORMAT(DATE_OF_BIRTH, '%m') = 3 AND GENDER = 'W' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID