-- 코드를 작성해주세요
-- 1. 가장 많은 리뷰를 작성한 회원의 ID를 찾는 CTE 정의
WITH TOP_REVIEWER AS (
    SELECT
        MEMBER_ID
    FROM
        REST_REVIEW
    GROUP BY
        MEMBER_ID
    ORDER BY
        COUNT(REVIEW_ID) DESC
    LIMIT 1
)

-- 2. 해당 회원의 리뷰 목록을 조회
SELECT
    P.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    MEMBER_PROFILE AS P
JOIN
    REST_REVIEW AS R ON P.MEMBER_ID = R.MEMBER_ID
WHERE
    P.MEMBER_ID = (SELECT MEMBER_ID FROM TOP_REVIEWER)
ORDER BY
    REVIEW_DATE ASC, REVIEW_TEXT ASC;