SELECT
    EXTRACT(YEAR FROM DIFFERENTIATION_DATE) YEAR,
    (MAX(SIZE_OF_COLONY) OVER (PARTITION BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE))
     - SIZE_OF_COLONY) YEAR_DEV,
    ID
FROM ECOLI_DATA
ORDER BY YEAR ASC, YEAR_DEV ASC;